### ISSUE TITLE
Cannot get it to work on CentOS 7 and Fedora 26

### ISSUE THREAD

**Issue by neubauerf** [ben-cohen/transient_token#1]
After compiling the code and manually copying the files to the correct dirs (in CentOS and Fedora the pam module needs to go to /lib64/security) it segfaults when authenticating. This is the error I can trace in with journalctl:

Stack trace of thread 2905:
 #0  0x00007fd862c4127f __rawmemchr (libc.so.6)
 #1  0x00007fd862c26292 _IO_str_init_static_internal (libc.so.6)
 #2  0x00007fd862c12cbd __isoc99_vsscanf (libc.so.6)
 #3  0x00007fd862c12c24 __isoc99_sscanf (libc.so.6)
 #4  0x00007fd8597dda82 pam_sm_authenticate (pam_transient_token.so)
 #5  0x00007fd863195e71 _pam_dispatch (libpam.so.0)
 #6  0x00007fd86319573b pam_authenticate (libpam.so.0)
 #7  0x000055ceab4d8892 auth_userpass (xrdp-sesman)
 #8  0x000055ceab4d5f5e scp_v0_process (xrdp-sesman)
 #9  0x000055ceab4d5e70 scp_process_start (xrdp-sesman)
 #10 0x000055ceab4d41f7 main (xrdp-sesman)
 #11 0x00007fd862bc34da __libc_start_main (libc.so.6)
 #12 0x000055ceab4d44aa _start (xrdp-sesman)

Any hints on getting this working? Great way to authenticate in our environment :)

**Comment by ben-cohen** [comment]
Thanks :)
I can't think what the problem might be right now.  Perhaps the return code of snprintf() was bad - e.g. -1 - so that the token format in pam_sm_authenticate() contained garbage for sscanf(), so I have fixed that.  (Unfortunately if that was the case then it will now just fail instead of crashing.)

Could you try using the logging I have added: uncomment the line in pam_transient_token.c to define DEBUG and then install (and restart service xrdp).  Then can you send me the line from /var/log/auth.log (or other log file) like this, please:

    pam_transient_token.so: Token is 'TTK1000:5878:MqsiWc0kMeu4Kk3iYOTm3nysHkPvbKq6' and token_format is 'TTK%d:%d:%16[A-Za-z0-9+/]%16[A-Za-z0-9+/]'

**Comment by ben-cohen** [comment]
PS The DEBUG option may also output passwords to the log file (e.g. if you set up PAM to try both transient-token and unix auth) so don't leave it enabled!

**Comment by neubauerf** [comment]
Hi! Thanks for you reply :).. Just tried it out, but the token always returns '(null)' and segfaults

pam_transient_token.so[2813]: Token is '(null)' and token_format is 'TTK%d:%d:%16[A-Za-z0-9+/]%16[A-Za-z0-9+/]'

Do I need to specify something in the xrdp.ini or sesman.ini?

My xrdp.ini section looks like this (only Xorg enabled):
[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20

The rest untouched

**Comment by ben-cohen** [comment]
Thanks - I wasn't expecting token to be NULL!  I have pushed a fix to make pam_sm_authenticate() return an error in this case.
This should make it no longer crash for you.  However, I don't know whether PAM will then refuse the login or if it will try again with a non-NULL password.

**Comment by ben-cohen** [comment]
I understand this now and have pushed another commit to fix it which you will need for it to work.

It is because PAM doesn't automatically prompt for a password but the modules have to do so; however, if a second PAM module is called (e.g. pam_transient_token after pam_unix as in unix-or-token-auth) then later modules can use the password already obtained.  If pam_transient_token is the first - or only - auth module then it doesn't to ask for a password.

**Summary of changes**

Main fix to obtain the token (see commit text for more info):

9fb3a91 Get authentication token if none is cached

Things to make it more robust:

0c1b731 Error if PAM returns a NULL user
eb2c559 pam_sm_authenticate should cope with NULL token
e36f962 Use sizeof() for udspath
a49f90e Check snprintf rc more carefully in pam_sm_authenticate() (2)
7cbd785 Check snprintf rc more carefully in pam_sm_authenticate()

Optional debugging:

e07b237 Add optional debugging

**Comment by neubauerf** [comment]
Works perfect! :) 

pam_transient_token.so[8437]: Token is 'TTK1000:8439:+tDsw9h3Mac4Wd6Rci39+3UIQCpSaiMk' and token_format is 'TTK%d:%d:%16[A-Za-z0-9+/]%16[A-Za-z0-9+/]'

xrdp-sesman[8437]: (8437)(140634433025856)[INFO ] ++ created session (access granted): username fred, ip 192.168.22.100:58094 - socket: 12
xrdp-sesman[8437]: (8437)(140634433025856)[INFO ] starting Xorg session...

Thank you very much!

**Comment by ben-cohen** [comment]
Great, thanks for letting me know!
